version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  dashboard-app:
    image: dashboard-app-image
    container_name: dashboard-app
    ports:
      - "8080:8080"
    networks:
      - monitoring
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:
  pgdata: {}